"""Update AdRequest model

Revision ID: 3da75f562368
Revises: 95d71c147ba9
Create Date: 2024-08-01 22:54:25.702036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da75f562368'
down_revision = '95d71c147ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sponsor_id', sa.Integer(), nullable=True))
        # Name the foreign key constraint
        batch_op.create_foreign_key(
            'fk_adrequest_sponsor',  # Name of the constraint
            'user',  # Table name of the referenced table
            ['sponsor_id'],  # Column name in the current table
            ['id']  # Column name in the referenced table
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        # Drop the constraint by name
        batch_op.drop_constraint('fk_adrequest_sponsor', type_='foreignkey')
        batch_op.drop_column('sponsor_id')

    # ### end Alembic commands ###
